version: "3.8"
services:
  e-commerce-product-page:
    container_name: e-commerce-product-page
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: JDFIREX
      POSTGRES_PASSWORD: JDFIREX
      POSTGRES_DB: e-commerce-product-page
    depends_on:
      - postgres
    env_file:
      - .env

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: mysecret42
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: JDFIREX
            password: JDFIREX

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: JDFIREX
      POSTGRES_PASSWORD: JDFIREX
      POSTGRES_DB: e-commerce-product-page
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    name: e-commerce-product-page
